export enum CompetitorOrigin {
  DROGAL = 'DROGAL',
  DROGASIL = 'DROGASIL',
  PAGUE_MENOS = 'PAGUE_MENOS',
  IKESAKI = 'IKESAKI',
  MICHELASSI = 'MICHELASSI',
  PACHECO = 'PACHECO',
  SAO_PAULO = 'SAO_PAULO',
  VENANCIO = 'VENANCIO',
  INDIANA = 'INDIANA',
}
