export const EXPORT_COLUMNS = [
  'ean',
  'name',
  'curve',
  'book',
  'price',
  'description',
  'average_unit_cost',
  'unit_sale_price',
  'drogal_name',
  'drogasil_name',
  'pague_menos_name',
  'ikesaki_name',
  'michelassi_name',
  'drogasil_category',
  'drogasil_weight',
  'drogal_price',
  'drogasil_price',
  'pague_menos_price',
  'ikesaki_price',
  'michelassi_price',
  'drogal_observation',
  'drogasil_observation',
  'pague_menos_observation',
  'ikesaki_observation',
  'drogal_error',
  'drogasil_error',
  'pague_menos_error',
  'ikesaki_error',
  'michelassi_error',
  'drogal_one_stock',
  'drogasil_one_stock',
  'michelassi_one_stock',
  'drogal_two_stock',
  'drogal_main_image',
  'drogasil_main_image',
  'pague_menos_main_image',
  'ikesaki_main_image',
  'michelassi_main_image',
  'drogal_images',
  'drogasil_images',
  'pague_menos_images',
  'ikesaki_images',
  'base_product_images'
] as const;

export type ExportColumn = typeof EXPORT_COLUMNS[number];
