export const IMPORT_PROCESS_EVENT = 'IMPORT_PROCESS_EVENT';

export const IMPORT_DROGAL_STOCK_USE_CASE = 'IMPORT_DROGAL_STOCK_USE_CASE';
export const IMPORT_DROGASIL_STOCK_USE_CASE = 'IMPORT_DROGASIL_STOCK_USE_CASE';

export const IMPORT_PRODUCTS_DROGAL_USE_CASE = 'IMPORT_PRODUCTS_DROGAL_USE_CASE';
export const IMPORT_PRODUCTS_DROGASIL_USE_CASE = 'IMPORT_PRODUCTS_DROGASIL_USE_CASE';
export const IMPORT_PRODUCTS_PAGUE_MENOS_USE_CASE = 'IMPORT_PRODUCTS_PAGUE_MENOS_USE_CASE';
export const IMPORT_PRODUCTS_IKESAKI_USE_CASE = 'IMPORT_PRODUCTS_IKESAKI_USE_CASE';
export const IMPORT_PRODUCTS_MICHELASSI_USE_CASE = 'IMPORT_PRODUCTS_MICHELASSI_USE_CASE';

export const GENERATE_BASE_PRODUCT_DESCRIPTION_USE_CASE = 'GENERATE_BASE_PRODUCT_DESCRIPTION_USE_CASE';
export const GENERATE_BASE_PRODUCT_IMAGES_USE_CASE = 'GENERATE_BASE_PRODUCT_IMAGES_USE_CASE';

export const SYNCHRONIZE_BASE_PRODUCT_USE_CASE = 'SYNCHRONIZE_BASE_PRODUCT_USE_CASE';
export const SYNCHRONIZE_BASE_PRODUCT_STOCK_USE_CASE = 'SYNCHRONIZE_BASE_PRODUCT_STOCK_USE_CASE';
export const SYNCHRONIZE_BASE_PRODUCT_METRICS_USE_CASE = 'SYNCHRONIZE_BASE_PRODUCT_METRICS_USE_CASE';
export const SYNCHRONIZE_ACTIVE_INGREDIENTS_USE_CASE = 'SYNCHRONIZE_ACTIVE_INGREDIENTS_USE_CASE';

export const IMPORT_BASE_PRODUCTS_CSV_USE_CASE = 'IMPORT_BASE_PRODUCTS_CSV_USE_CASE';

export const GENERATE_BASE_PRODUCT_PROPERTIES_USE_CASE = 'GENERATE_BASE_PRODUCT_PROPERTIES_USE_CASE';

export const SYNCHRONIZE_OFFER_BOOKS_INFO_USE_CASE = 'SYNCHRONIZE_OFFER_BOOKS_INFO_USE_CASE';

export const EXECUTE_OFFER_BOOK_RULES_EVENT = 'EXECUTE_OFFER_BOOK_RULES_EVENT';
